name: Hurl Tests

on: [push, pull_request]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Hurl
        run: |
          sudo apt-get update
          curl -fsSL https://apt.akeeba.com/akeeba-apt.gpg | sudo tee /etc/apt/trusted.gpg.d/akeeba.asc >/dev/null
          echo "deb [signed-by=/etc/apt/trusted.gpg.d/akeeba.asc] https://apt.akeeba.com stable main" | sudo tee /etc/apt/sources.list.d/akeeba.list
          sudo apt-get update && sudo apt-get install -y hurl

      - name: Run Tests
        run: |
          hurl --variables-file .\vars.env --test .\tests hurl-report

      - name: Upload HTML Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: hurl-html-report
          path: hurl-report
          retention-days: 7
