name: Hurl Tests

on: [push, pull_request]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Hurl
        run: |
          HURL_VERSION=$(curl -s https://api.github.com/repos/Orange-OpenSource/hurl/releases/latest | grep -oP '"tag_name": "\K(.*)(?=")')
          curl -LO "https://github.com/Orange-OpenSource/hurl/releases/download/${HURL_VERSION}/hurl_${HURL_VERSION}_linux_x86_64.deb"
          sudo dpkg -i "hurl_${HURL_VERSION}_linux_x86_64.deb"
          rm "hurl_${HURL_VERSION}_linux_x86_64.deb"

      - name: Run Tests
        run: |
          hurl --variables-file .\vars.env --test .\tests hurl-report

      - name: Upload HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: hurl-html-report
          path: hurl-report
          retention-days: 7
